#!/usr/bin/env node
const fs=require("fs");
const locations=JSON.parse(fs.readFileSync("data/tracked-locations.json","utf8"));
const H={"User-Agent":"StormWatch/1.0 github.com/nycguy/stormwatch","Accept":"application/geo+json"},NOAA_STATIONS="https://api.tidesandcurrents.noaa.gov/mdapi/prod/webapi/stations.json?type=waterlevels";
async function json(u){const r=await fetch(u,{headers:H});if(!r.ok)throw Error(r.status+" "+u);return r.json()}
let stationCache=null;async function stationCatalog(){if(!stationCache)stationCache=json(NOAA_STATIONS);return stationCache}
async function coastal(lat,lon){try{const stations=await stationCatalog(),R=6371,rad=Math.PI/180,dist=(a,b,c,d)=>{const x=(c-a)*rad,y=(d-b)*rad,A=Math.sin(x/2)**2+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(A))},ss=(stations.stations||[]).map(v=>({...v,km:dist(lat,lon,+v.lat,+(v.lng??v.lon))})).filter(v=>v.km<=120).sort((a,b)=>a.km-b.km);if(!ss[0])return null;const id=ss[0].id,q=new URLSearchParams({date:"latest",station:id,product:"water_level",datum:"MLLW",time_zone:"gmt",units:"english",format:"json"}),w=await json("https://api.tidesandcurrents.noaa.gov/api/prod/datagetter?"+q),v=w.data?.[0];return v?{station:String(id),name:ss[0].name,distanceKm:ss[0].km,waterLevelFt:+v.v,waterTime:v.t}:null}catch{return null}}
async function one(x){try{const p=await json(`https://api.weather.gov/points/${x.lat},${x.lon}`);const [a,f,coast]=await Promise.all([json(`https://api.weather.gov/alerts/active?point=${x.lat},${x.lon}`),json(p.properties.forecast),coastal(x.lat,x.lon)]),periods=f.properties.periods||[],winds=periods.flatMap(v=>(v.windSpeed||"").match(/\d+/g)||[]).map(Number);return{...x,capturedAt:new Date().toISOString(),cwa:p.properties.cwa,alertCount:(a.features||[]).length,alerts:(a.features||[]).slice(0,8).map(v=>v.properties.event),peakWindMph:winds.length?Math.max(...winds):null,coastal:coast,periods:periods.slice(0,8).map(v=>({name:v.name,startTime:v.startTime,temperature:v.temperature,unit:v.temperatureUnit,shortForecast:v.shortForecast,windSpeed:v.windSpeed,windDirection:v.windDirection}))}}catch(e){return{...x,capturedAt:new Date().toISOString(),error:String(e.message||e)}}}
(async()=>{const dir="data/history",today=new Date().toISOString().slice(0,10);fs.mkdirSync(dir,{recursive:true});const current=await Promise.all(locations.map(one)),ok=current.filter(x=>!x.error).length;if(!ok)throw Error("All tracked location captures failed");fs.writeFileSync("data/current.json",JSON.stringify({generatedAt:new Date().toISOString(),successful:ok,total:current.length,locations:current},null,2)+"\n");const path=`${dir}/${today}.json`,old=fs.existsSync(path)?JSON.parse(fs.readFileSync(path,"utf8")):[];old.push({capturedAt:new Date().toISOString(),locations:current});fs.writeFileSync(path,JSON.stringify(old.slice(-96),null,2)+"\n");console.log("Captured",ok,"of",current.length,"locations")})().catch(e=>{console.error(e);process.exit(1)});
